---
- name: Verify
  hosts: all
  gather_facts: false
  become: no
  tasks:
    - name: Query metamod version
      command: rcon -p 27015 -H 127.0.0.1 -P srht sm plugins list
      register: rcon
    - assert:
        that:
          - rcon.rc == 0
          - rcon.stdout_lines | select('search', 'GunGame:SM') != []
